### ISSUE TITLE
Is it possible to set radius on DB?

### ISSUE THREAD

**Issue by ozican** [MichaelSolati/geofirestore-js#173]
On my app, I have clients and shoppings.

Shoppings set the radius of their service area. So my question is, is it possible to set it on DB side?

Clients search the shoppings which are near. But for example a shopping dont want to deliver 2 mile but other wants... How can I seperate this?

**Comment by MichaelSolati** [comment]
Hey @ozican, so I'm not exactly sure what you're looking to do... [`GeoQuery` objects](https://geofirestore.com/classes/_geoquery_.geoquery.html) (such as a [`GeoCollectionReference `](https://geofirestore.com/classes/_geocollectionreference_.geocollectionreference.html)) have a [`near` method](https://geofirestore.com/classes/_geoquery_.geoquery.html#near) which can take an [query criteria argument](https://geofirestore.com/interfaces/_geofirestoretypes_.geofirestoretypes.querycriteria.html) which includes the radius for the query...

Could you provide an example of what you're trying to achieve?
