### ISSUE TITLE
always returns empty array and when 0 returns all

### ISSUE THREAD

**Issue by IamNotHuman** [MichaelSolati/geofirestore-js#174]
When ever I add a value to radius the query stops bringing data.

I have a collection called zones and a field called location that has firestore geopoints.

using:
geofirestore@3.4.3
react-native-firebase/firestore@6.4.0

my code:
>
 const getZones = async (location) => {
    const geofirestore = new GeoFirestore(firestore());
    const geocollection = geofirestore.collection('zones');

    return geocollection.limit(100).near({
        center: new firestore.GeoPoint(location.latitude, location.longitude),
        radius: 100
    })
        .get()
        .then(snapshot => {
            console.log(snapshot, '.................')
            let markers = [];
            snapshot.docChanges().forEach(change => {
                markers.push({id: change.doc.id, ...change.doc.data()});
            });
            return markers;
        });
}

**Comment by MichaelSolati** [comment]
[`get` only executes once](https://geofirestore.com/classes/_geoquery_.geoquery.html#get). You want [`onSnapshot`](https://geofirestore.com/classes/_geoquery_.geoquery.html#onsnapshot) to get changes to Firestore. (I think this should help)

**Comment by IamNotHuman** [comment]
> [`get` only executes once](https://geofirestore.com/classes/_geoquery_.geoquery.html#get). You want [`onSnapshot`](https://geofirestore.com/classes/_geoquery_.geoquery.html#onsnapshot) to get changes to Firestore. (I think this should help)

Changed it to onSnapshot but getting the same result (when I add radius nothing happens and when I add radius 0 I get all of the markers)


```
const geofirestore = new GeoFirestore(firestore());
    const geocollection = geofirestore.collection('zones');

    return geocollection.limit(100).near({
        center: new firestore.GeoPoint(location.latitude, location.longitude),
        radius: 100
    }).onSnapshot((snapshot: GeoQuerySnapshot) => {
        let markers = [];
        snapshot.forEach(doc => {
            markers.push({id: doc.id, ...doc.data()});
        });
        dispatch(ACTIONS.setPostMarkers(markers));
    });
```

**Comment by MichaelSolati** [comment]
Can I get a repo where this issue is reproducible?

**Comment by FrancisLeigh** [comment]
@MichaelSolati  I am experiencing this also. `radius: 0` returns all results whereas any other number returns none.

```
import { useFirestore } from "react-redux-firebase";
import { GeoFirestore } from "geofirestore";
...

const firestore = useFirestore();
const geofirestore = new GeoFirestore(firestore);
const geocollection = geofirestore.collection("shops");
const locations = [
    {
        latitude: 50.819224,
        longitude: -0.122760,
        name: "Barber Blacksheep",
    },
    {
        latitude: 50.819583,
        longitude: -0.124165,
        name: "Sharp Scissors",
    },
    {
        latitude: 50.819217,
        longitude: -0.124777,
        name: "Zar's Barbers",
    },
    {
        latitude: 50.830493,
        longitude: -0.147061,
        name: "Teddy Edwards",
    },
    {
        latitude: 40.7589,
        longitude: -73.9851,
        name: "TEST",
    },
];

useEffect(() => {
    locations.forEach((l) => {
        geocollection.add({
            name: l.name,
            coordinates: new firestore.GeoPoint(l.longitude, l.latitude),
        });
    });

    const query = geocollection.near({
        center: new firestore.GeoPoint(50.818398, -0.12713671),
        radius: 0,
    }).get().then((value) => {
        console.log(value.docs.map((d) => d.data()));
    });
}, []);
```

If i were to put the `radius: 1000000` it yields no "shops" where `0` yields all `5`
