### ISSUE TITLE
Near method returns no values for negative center coordinates.

### ISSUE THREAD

**Issue by mszubiczuk** [MichaelSolati/geofirestore-js#183]
- Operating System version: macOS
- Firebase library: "firebase-admin": "^8.10.0",
- GeoFirestore version: 4.1.0, previously 4.0.1

Hi, I've been having issues with fetching data with negative coordinates ( South, West ) set for `center` parameter. 
It works just fine, when `center` has positive longitude and latitude values.
Down below there is a code snippet of how data are being saved in firestore, and also how near query is implemented.

```JavaScript
functions.firestore
    .document(`${CollectionNames.restaurants}/{restaurantId}`)
    .onUpdate(async (change, context) => {
        const newValue = change.after.data();
        const id = context.params['restaurantId'];
        
        const geoFirestore = new GeoFirestore(firestore());
        const documentReference = geoFirestore
            .collection(CollectionNames.restaurants)
            .doc(id);
        const document = newValue;

        document['coordinates'] = new firestore.GeoPoint(newValue.latitude, newValue.longitude);

        return documentReference.set(document);
    });
```
This code updates documents correctly and results in geofirestore related fields being added:
<img width="388" alt="Screenshot 2020-07-03 at 13 00 46" src="https://user-images.githubusercontent.com/28589204/86463239-68f0a200-bd2d-11ea-99cc-eb56ad68f08b.png">

Anyway, when longitude and latitude are positive, there are no issues whatsoever.

However, code below returns no results when `lat` or `long` or both are negative.
Also, if one or both restaurant coordinates is negative, these documents are not returned even if radius is set to extra large number ( 10000000000000000000 etc. ).

```JavaScript
import { GeoFirestore } from 'geofirestore';
import {firestore} from "firebase-admin";

const geoFirestore = new GeoFirestore(firestore());

const geoCollection = geoFirestore.collection(CollectionNames.restaurants);

    const geoLocationSnapshot = await geoCollection
        .near({
            center: new firestore.GeoPoint(lat, long),
            radius,
        })
        .get();
```

**Comment by MichaelSolati** [comment]
So I'm partially able to recreate this issue, and partially unable...

[Here is a StackBlitz](https://stackblitz.com/edit/geofirestore-183?file=index.ts) where I have coordinates of [1, 1], [1, -1], [-1, -1], [-1, 1] (4 quadrants on a plane) and I'm able to query from [0, 0] and get all 4 of them (as well as a few others I did). Pretty much geohashes fall apart with a radius greater than 8587 KM.

Keep in mind geohashes aren't a perfect fix for the lack of proper geoqueries in Firestore. I think I need to know what the center and radius are for your query, as well as what geopoints that you'd expect to have returned.

**Comment by MichaelSolati** [comment]
For reference this distance between San Francisco to London is 8611 KM, just outside of the range supported. Mind you, that's a massive space. I give that as a reference as to how much space can be covered by 8587 KM.
