### ISSUE TITLE
Geoquery on Non Geo Collection which has a Geo Subcollection -  Querying on Collection Group

### ISSUE THREAD

**Issue by maheshwara-bwd** [MichaelSolati/geofirestore-js#187]
Hi ,

I have a subcollection created with geofirestore inside a normal firestore collection.
**Eg:**
**User(Collection) -> document -> Address(Geo Subcollection)**

I want to use **near** query on **User Collection** to find out all the documents which is near to the given input address

Is it possible to do this ?

Pleas help me on this

Thanks in advance

**Comment by MichaelSolati** [comment]
Just to ensure I'm understanding you correctly. Do you intend to search through all the the sub collections from all users, ie a [collection group query](https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query)?

**Comment by maheshwara-bwd** [comment]
Yes exactly,

I have to search through all the user's addresses to find out the address within a range.

Here **User** is a **collection** and **Addresses** are **Geo subcollection**

How could i achieve this?

**Comment by MichaelSolati** [comment]
I haven't introduced `collectionGroup` but can look to add that over the course of the next week or so. Unfortunately you'll need to bear with me!

**Comment by maheshwara-bwd** [comment]
And also is

> I haven't introduced `collectionGroup` but can look to add that over the course of the next week or so. Unfortunately you'll need to bear with me!

Thanks for your quick reply and sorting it out,
Guess i need to find an work around.
