### ISSUE TITLE
Typescript Error: Argument of type 'Firestore' is not assignable to parameter of type 'firebase.firestore.Firestore | FirebaseFirestore.Firestore'.

### ISSUE THREAD

**Issue by lsps9150414** [MichaelSolati/geofirestore-js#188]
### [REQUIRED] Describe your environment

- "geofirestore": "^4.2.1",
- "firebase": "7.9.0",

#### Describe the bug

Getting
`Argument of type 'Firestore' is not assignable to parameter of type 'firebase.firestore.Firestore | FirebaseFirestore.Firestore'.`
when
`const geoFirestore = geofirestore.initializeApp(firebase.firestore());`

![image](https://user-images.githubusercontent.com/5022617/88037300-4a850600-cb77-11ea-9656-f0aba5f89cd0.png)

#### Steps to Reproduce

3. Scroll to '....'

#### Relevant Code

Reproduce the issue on StackBlitz and provide your forked URL or provide sample code below

https://stackblitz.com/fork/geofirestore-issue-sandbox

```JavaScript
// TODO(you): code here to reproduce the problem
```

**Comment by MichaelSolati** [comment]
Can you please provide an example repo or stackblitz where this can be observed?

**Comment by MichaelSolati** [comment]
@lsps9150414 I just wanted to see if there was anything more you could share to help me identify and help solve your problem.

**Comment by moulie415** [comment]
@lsps9150414 I had the same problem and after updating firebase it went away I am now on

```
"firebase": "^7.21.0",
"geofirestore": "^4.3.0"
```

**Comment by MichaelSolati** [comment]
@moulie415 can you provide a repo where this issue is reproducable?

**Comment by Tj3n** [comment]
@MichaelSolati  I also having this issue, problem is that I'm having different firebase version (8.2.3) in my project, and the geofirestore-core compare it with different version of firestore (8.4.1?), I have to use `// eslint-disable-next-line @typescript-eslint/ban-ts-comment  // @ts-ignore` to avoid this

**Comment by MichaelSolati** [comment]
@Tj3n can you provide a repo where this issue is reproduceable?

**Comment by sachi097** [comment]
@MichaelSolati I am faced with this issue after updating @angular/fire to v7.1.1 and with current version of geofirestore.
Unfortunately I cannot provide you with the repo since it is private. 

Please resolve this issue since most of the us would be migrating to @angular/fire v7 and firebase v9

**Comment by sdeprada** [comment]
Hi, I'm getting the same error after upgrading @angular/fire from v6.1.4 to 7.2.0 and firebase from v8.6.2 to v9.6.4

There is a breaking change in AngularFire v7 and to maintain compatibility, you have to change firebase import to:
`import firebase from 'firebase/compat/app';`
And I suppose that there is the root of the conflict

In my case, I solved simply ignoring the error with
`// @ts-ignore`
At runtime it is working well
