### ISSUE TITLE
query on collectionGroup is going weird.

### ISSUE THREAD

**Issue by kosuel** [MichaelSolati/geofirestore-js#192]
- Operating System version: firebase http trigger
- Browser version: none
- Firebase library (`firebase`, `firebase-admin`, etc...) and version:
    "firebase-admin": "^8.10.0",
    "firebase-functions": "^3.6.1",
- GeoFirestore version: 4.3.0

There are collection groups called 'inventories'. When I query on collection group, geofirestore returns only one result.

#### Steps to Reproduce
There are two users and they have their own inventory like below.

users/kosuel/inventories/marble
users/yuna/inventories/dchero

And I query with below code.

```
const query = geoFirestore.collectionGroup('inventories')
                    .near({ center: new admin.firestore.GeoPoint(data.latitude, data.longitude), radius: radiusInKm })

const querySnapshot = await query.get();

```

This returns only one result instead of two no matter how large radius I give.
This code runs in firebase http trigger so I can't use onSnapshot function on query.

**Comment by MichaelSolati** [comment]
I'm sorry I took forever to get to this, but I think I may have possibly pinned down the issue. The error logging I got from firebase was less than ideal so I had to do some googling to find this. Anyway, from what I can best tell, this is an indexing issue.

We'll need to create a new index which you can do here:

https://console.firebase.google.com/u/0/project/<YOUR_PROJECT_ID_HERE>/firestore/indexes/single-field/manage

In the exemptions area click "Add exemption." Then fill out the two steps as you see below...

![Screenshot 2020-11-30 113214](https://user-images.githubusercontent.com/11811422/100655727-876cc080-3300-11eb-985f-01638d4f5a9c.png)

![2](https://user-images.githubusercontent.com/11811422/100655741-8cca0b00-3300-11eb-83bf-392e77b503a8.png)

I found this issue helpful in resolving this issue => invertase/react-native-firebase#3737

Please let me know if this helps or works for you, if I don't hear back I'm going to close out the issue in about a week.
