### ISSUE TITLE
Custom Key no results

### ISSUE THREAD

**Issue by MarcoCarnevali** [MichaelSolati/geofirestore-js#199]
Hello, what I understand is that now it's possible to define a custom data structure per this issue https://github.com/MichaelSolati/geofirestore-js/issues/185
as a lack of examples I still not understand how the implementation should be.
This is my code in which I initialize GeoFirestore and the collection. "location.coordinate" is where I have the GeoPoint, but it can't find any results
```
    const gf = geofirestore.initializeApp(db)
    const collection = gf.collection("Users", "location.coordinate")
```
Thank you in advance!

**Comment by MichaelSolati** [comment]
Can you show/share your full query? Like how/when you you add a doc and search for docs?

**Comment by manojsethi** [comment]
I am facing this issue @MarcoCarnevali can you guide how did you resolved it.
