### ISSUE TITLE
Geofirestore android not compatiable with geofirestore js

### ISSUE THREAD

**Issue by RafiHasani** [MichaelSolati/geofirestore-js#200]
### [REQUIRED] Describe the problem
Geofirestore android library data structure is not compatible with javascript data.

geofirestore js lib uses this data structured:

interface GeoDocumentData {
  g: {
    geohash: string;
    geopoint: GeoPoint;
  };
  [field: string]: any;
  } 
 however android lib stores data 
interface GeoDocumentData {
  g: string;
  l: GeoPoint;
  };
  }

actually it is not a bug. but i tried this for 2 week then i realized the compatibility issue. could you make some changes in android java library so it work together properly.
I am using geofirestore android java version with cloud function in JavaScript. so please direct me if there is minor changes i could make in my code. because i am doing my final year project and i am stuck on this.
thank you for consideration.
with regards

**Comment by MichaelSolati** [comment]
@RafiHasani I'm sorry to say, I don't maintain the Android library. Its a completely separate project [maintained here](https://github.com/imperiumlabs/GeoFirestore-Android). Unfortunately I doubt you'll get proper cross library support. However you could consider using Firebase's [Cloud Functions](https://firebase.google.com/docs/functions/callable) in your Android app to get and set data to your Firestore Collection and use this library in the Cloud Functions.
