### ISSUE TITLE
Perform a query with inequality / not equals

### ISSUE THREAD

**Issue by SnowBases** [MichaelSolati/geofirestore-js#202]
I wonder if we can add _'!='_ and _'not-in'_ inside WhereFilterOp. because it said that Firebase release notes suggest there are now not-in and != queries. (Proper documentation is now available.) 
https://stackoverflow.com/questions/47251919/firestore-how-to-perform-a-query-with-inequality-not-equals

Is there any way to add this inequality? 

```
export type WhereFilterOp =
    | '<'
    | '<='
    | '=='
    | '!='
    | '>='
    | '>'
    | 'array-contains'
    | 'in'
    | 'array-contains-any'
    | 'not-in';
```

Currently, geofirestore only supports this:
![image](https://user-images.githubusercontent.com/31583701/101480659-f4322b80-398e-11eb-818a-8c65346de181.png)

Great tool anyway!

**Comment by MichaelSolati** [comment]
Hey @SnowBases I updated the core library to use the proper inequalities (as well as this library to use the new core). Update to v4.4.1 and you should be all set.
