### ISSUE TITLE
Pass a custom document ID 

### ISSUE THREAD

**Issue by ryancoughlin** [MichaelSolati/geofirestore-js#222]
Is there a way to pass a document ID when running `add`? I've been reading through the docs and doesn't seem like I can, but wanted to confirm.

I am looking up the nearest tide station to the user. This returns a `station_id` that is passed to NOAA to fetch results for that station.

`DocumentData` does not pass back custom values when I seeded the database:

E.g

```
    {
        "exists": true,
        "id": "DwmpTfFUdZ7cTZa9Y81z",
        "distance": 14.558592542031368
    },

```

Is it possible to pass a document ID or display another key, value pair inside of the data coming back from a query?

Thank you

**Comment by MichaelSolati** [comment]
You can't with the `add` syntax, Firebase autogenerates the ID with add. What you would want to look at is `set`. So you'd do something like

```
const seedItem = {
    "exists": true,
    "id": "DwmpTfFUdZ7cTZa9Y81z",
    "distance": 14.558592542031368
};

// So we're telling firestore that this is the doc that we want to modify even though it doesn't exist yet, but we create it by setting a value to is.
geocollection.doc(seedItem.id).set(seedItem);
```
