### ISSUE TITLE
Query returning zero results when filtering with where

### ISSUE THREAD

**Issue by smolugu** [MichaelSolati/geofirestore-js#223]
I am using geofirestore ^3.4.1. Have created an index when prompted but the query returns zero results.

`const query = userCollectionRef.where('tags', 'array-contains-any', keys).
                near({
                    center: gp,
                    radius: radius,
                });`

can anyone tell me what I could be missing?

Regards,

**Comment by MichaelSolati** [comment]
Usually, not always, this is an indexing issue (aka a missing index)

1) What do your [indexes](https://firebase.google.com/docs/firestore/query-data/indexing) look like?
2) I'm not seeing you resolve this query... `near` returns a geoquery object which you'll need to call [`onSnapshot`](https://geofirestore.com/classes/geoquery.geoquery-1.html#onsnapshot) or [`get`](https://geofirestore.com/classes/geoquery.geoquery-1.html#get) on. Assuming you're doing one of these, can you add an error catch to it and share the results if it logs an error? If it is an indexing error this should log and provide a link to generate the correct index.

**Comment by smolugu** [comment]
Hi, The index is created on d.tags Arrays, g Ascending. 

I am using get on the query. There is no error in the logs and the docs in the resulting querySnapshot is always empty.

I tried to create the index manually but it is not recognized.

Have also tried deleting the index and creating it again multiple times.

`const query = userCollectionRef.where('tags', 'array-contains-any', keys).
                near({
                    center: gp,
                    radius: radius,
                });

            try {
                const value = await query.get();
                console.log('query result: ' + value);
                const userDocs = value.docs;
                console.log('userDocs length: ' + userDocs.length);
                console.log('userDocs: ' + userDocs);

                userDocs.forEach(element => {
                   console.log('element value:' + element.data().id);
                });

            } catch (err) {
                console.log('geofirestore error: ' + err);
            }`

**Comment by smolugu** [comment]
Hi, The index is created on d.tags Arrays, g Ascending.

I am using get on the query. There is no error in the logs and the docs in the resulting querySnapshot is always empty.

I tried to create the index manually but it is not recognized.

Have also tried deleting the index and creating it again multiple times.
`const query = userCollectionRef.where('tags', 'array-contains-any', keys).
                near({
                    center: gp,
                    radius: radius,
                });
            try {
                const value = await query.get();
                console.log('query result: ' + value);
                const userDocs = value.docs;
                console.log('tokenDocs length: ' + userDocs.length);
                console.log('tokenDocs: ' + userDocs);
                userDocs.forEach(element => {
                    console.log('element value:' + element.data().token);
                });
            } catch (err) {
                console.log('geofirestore error: ' + err);
            }`

**Comment by MichaelSolati** [comment]
Can you share a screenshot of what a doc in your collection looks like, also are you using geofirestore to add the doc to the collection?

**Comment by smolugu** [comment]
I am using GeoFlutterFire in flutter app to add location info to the doc. The fields look as in the below screenshot. The indexes which I created when prompted while fetching records in the app are working fine.

will this be an issue. It never occurred to me as the regular queries worked fine in cloud function.

<img width="450" alt="Screen Shot 2021-12-22 at 9 08 18 AM" src="https://user-images.githubusercontent.com/8217755/147031678-4b9d0ae7-6dce-4385-8a44-1cb6a03ae049.png">

**Comment by smolugu** [comment]
@MichaelSolati I am planning on creating a separate collection adding documents with geofirestore. 

Also, just want to know if we can add a map with field name "d" and keys on which we want to create a composite index.

**Comment by spoxies** [comment]
Just a note: In my case(s) the queries return nothing, only if `'array-contains'` is used in the `where()` (but I'm on a different version). Currently trying to make sense of it. But I'm curious if it is the same for you @smolugu ?

Works:
`const query = userCollectionRef.near({ center: gp, radius: radius}).where('deleted', '==', false);`

Does not work:
`const query = userCollectionRef.near({ center: gp, radius: radius}).where('tags', 'array-contains-any', keys);`

**Comment by ZacharyHandshoe** [comment]
Any resolution for this?

**Comment by spoxies** [comment]
@ZacharyHandshoe It has been a while but what I note when looking to my code I have two indexes:
`g` and `g.geohash` that might be needed to facilitate such query: 

**Query**
```javascript
return geoUsersCollection
                .near({ center: geoPoint, radius: geoRadius })
                .where('deleted', '==', false)
                .where('subscriptions', 'array-contains', channel)
                .get()
```

**Indexes:**
```json
    {
      "collectionGroup": "users",
      "queryScope": "COLLECTION",
      "fields": [
        {
          "fieldPath": "subscriptions",
          "arrayConfig": "CONTAINS"
        },
        {
          "fieldPath": "deleted",
          "order": "ASCENDING"
        },
        {
          "fieldPath": "g.geohash",
          "order": "ASCENDING"
        }
      ]
    },
```


 ```json
 {
      "collectionGroup": "users",
      "queryScope": "COLLECTION",
      "fields": [
        {
          "fieldPath": "deleted",
          "order": "ASCENDING"
        },
        {
          "fieldPath": "subscriptions",
          "arrayConfig": "CONTAINS"
        },
        {
          "fieldPath": "g",
          "order": "ASCENDING"
        }
      ]
    },
```

If that is not the solution it might be working on my side because I'm running a [patched](https://github.com/spoxies/geofirestore-core/commit/894f4806c1a7d5c09033589a20f836cb3516687d) version of the geofirebase-core of this patch explained here: 
https://github.com/MichaelSolati/geofirestore-core/issues/6
